name: Build And Smoke Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m build

      - name: Run smoke test
        run: |
          pip install dist/*.whl
          python -c 'from bruvtab.tests.test_main import run_mocked_mediators as run; run(count=3, default_port_offset=0, delay=0)' &
          sleep 3
          bruvtab list
          bruvtab windows
          bruvtab clients
          bruvtab active
          bruvtab words
          bruvtab text
          bruvtab html
